account/urls.py
from django.conf.urls import url

from account import views

app_name = 'account'

urlpatterns = [
    url(r'^recover/', views.recover, name='recover'),
    url(r'^reset_password/$', views.reset_password, name='reset_password'),
    url(r'^reset_password/(?P<key>.*)/$', views.reset_password, name='reset_password_key'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^activate/(.*)/$', views.activate, name='activate'),
    url(r'^activation$', views.activation, name='activation'),
]

eprofile/urls.py
from django.conf.urls import url

from eprofile import views

app_name = 'profile'

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^update_cover_photo/$', views.update_cover_photo, name='update_cover_photo'),
    url(r'^update_profile_photo/$', views.update_profile_photo, name='update_profile_photo'),
    url(r'^update_card/$', views.update_card, name='update_card'),
    url(r'^update_summary/$', views.update_summary, name='update_summary'),
    url(r'^update_school/$', views.update_school, name='update_school'),
    url(r'^update_school/(?P<uuid>.*)/$', views.update_school, name='update_school_uuid'),
    url(r'^experience/$', views.experience, name='experience'),
    url(r'^experience/(?P<uuid>.*)/$', views.experience, name='update_experience'),
]

konect/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import patterns, include, url
from django.contrib import admin


from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^profile/', include('eprofile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url

from main import views
from eprofile import views as pView

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', pView.home, name='home'),
    url(r'^index/$', pView.home, name='default'),
]

eprofile/forms.py
import datetime
from django import forms

from eprofile.models import Profile, Education, Experience


MONTHS = [
    ('0', 'Month'),
    ('1', 'January'),
    ('2', 'February'),
    ('3', 'March'),
    ('4', 'April'),
    ('5', 'May'),
    ('6', 'June'),
    ('7', 'July'),
    ('8', 'August'),
    ('9', 'September'),
    ('10', 'October'),
    ('11', 'November'),
    ('12', 'December'),
]


def get_year_choices(year_from=True):
    year_choices = [('0', 'Year'),]
    start_year = datetime.date.today().year-61
    if year_from:
        for i in range(datetime.date.today().year, start_year, -1):
            year_choices.append((i, i))
    else:
        for i in range(datetime.date.today().year+10, start_year, -1):
            year_choices.append((i, i))

    return year_choices

class ImageUploadForm(forms.Form):
    img_file = forms.ImageField(
        label='Select an image'
    )


class ProfileCardForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['card_name', 'card_title', 'card_department', 'card_employer',
                  'card_email', 'card_address1', 'card_address2', 'card_phone', 'card_office']
        labels = {
            'card_name': 'Full name',
            'card_title': 'Current position',
            'card_department': 'Department',
            'card_employer': 'Institution',
            'card_address1': 'Street',
            'card_address2': 'City, ST Zip',
            'card_email': 'Email',
            'card_phone': 'Phone',
            'card_office': 'Office',
        }

        widgets = {
            """'card_name': forms.CharField(required=True, help_text='Full name with salution', widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_title': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_department': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_employer': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_address1': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_address2': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_email': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_phone': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            'card_office': forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'})),
            """
        }

    def __init__(self, *args, **kwargs):
        super(ProfileCardForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False
            self.fields[field].widget.attrs['class'] = 'form-control'

        self.fields['card_name'].required = True


class ProfileSummaryForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['summary']
        labels ={
            'summary': 'Update Summary',
        }

    def __init__(self, *args, **kwargs):
        super(ProfileSummaryForm, self).__init__(*args, **kwargs)
        self.fields['summary'].required = False
        self.fields['summary'].widget.attrs['class'] = 'form-control'


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['school', 'location', 'month_from', 'year_from', 'current', 'month_to',  'year_to', 'graduated', 'degree',
                  'major_field', 'concentrations', 'gpa', 'activities', 'societies', 'description']
        labels= {
            'school': 'College/School *',
            'location': 'Town/City, State',
            'gpa': 'GPA',
            'month_from': 'Month',
            'month_to': 'Month',
            'year_from': 'Year',
            'year_to': 'Year',
        }

    def __init__(self, *args, **kwargs):
        super(EducationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['month_from'] = forms.ChoiceField(choices=MONTHS)
        self.fields['month_to'] = forms.ChoiceField(choices=MONTHS)
        self.fields['year_from'] = forms.ChoiceField(choices=get_year_choices())
        self.fields['year_to'] = forms.ChoiceField(choices=get_year_choices(False))
        self.fields['activities'].widget.attrs['rows'] = 3
        self.fields['societies'].widget.attrs['rows'] = 3
        self.fields['description'].widget.attrs['rows'] = 5


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['company', 'location', 'month_from', 'year_from', 'month_to',
                  'year_to', 'title', 'current', 'description']
        labels= {
            'company': 'Company *',
            'location': 'Town/City, State',
            'month_from': 'Month',
            'month_to': 'Month',
            'year_from': 'Year',
            'year_to': 'Year',
            'title': 'Title *',
            'current': 'I currently work here',
        }

    def __init__(self, *args, **kwargs):
        super(ExperienceForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['month_from'] = forms.ChoiceField(choices=MONTHS)
        self.fields['month_to'] = forms.ChoiceField(choices=MONTHS)
        self.fields['year_from'] = forms.ChoiceField(choices=get_year_choices())
        self.fields['year_to'] = forms.ChoiceField(choices=get_year_choices(False))
        self.fields['description'].widget.attrs['rows'] = 5
        self.fields['current'].widget.attrs['class'] = ''

eprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from eprofile.models import Photo, Profile, Education, Experience
from eprofile.forms import ImageUploadForm, ProfileCardForm, ProfileSummaryForm, EducationForm, ExperienceForm
from main import utility


# Create your views here.


@login_required
def profile(request):
    user_profile = Profile.objects.get(user=request.user)
    site_url = utility.get_site_url(request)
    schools = Education.objects.filter(user=user_profile)
    user_profile.schools = schools
    user_profile.positions = Experience.objects.filter(user=user_profile)
    return render(request,
                  'eprofile/profile.html',
                  dict(user_profile=user_profile, site_url=site_url, ))


@login_required
def home(request):
    return profile(request)


@login_required
def edit_profile(request):
    profile = Profile(user=request.user)
    return HttpResponse('hello there!')


@login_required
def update_cover_photo(request):
    # Handle file upload
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            cover = Photo(user=request.user, photo=request.FILES['img_file'])
            cover.save()
            # print('name=', cover.photo.name)
            # print('path=', cover.photo.path)
            # print('url=', cover.photo.url)
            # Redirect to the document list after POST
            profile = Profile.objects.get(user=cover.user)
            profile.cover_photo = cover.photo.name
            profile.save(update_fields=['cover_photo'])
            return HttpResponseRedirect(reverse('profile:profile'))
    else:
        form = ImageUploadForm()  # A empty, unbound form

    message = ''
    return render(request,
                  'eprofile/photos.html',
                  dict(site_url=site_url,
                       form_heading='Upload Cover Photo',
                       instruction='Cover photo must be at least 300px tall and 900px wide.',
                       action=reverse('profile:update_cover_photo'),
                       form=form,
                       user_profile=user_profile))


@login_required
def update_profile_photo(request):
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    # Handle file upload
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            photo = Photo(user=request.user, photo=request.FILES['img_file'])
            photo.save()
            # print('name=', cover.photo.name)
            # print('path=', cover.photo.path)
            # print('url=', cover.photo.url)
            # Redirect to the document list after POST
            profile = Profile.objects.get(user=photo.user)
            profile.profile_photo = photo.photo.name
            profile.save(update_fields=['profile_photo'])
            return HttpResponseRedirect(reverse('profile:profile'))
    else:
        form = ImageUploadForm()  # A empty, unbound form

    return render(request,
                  'eprofile/photos.html',
                  dict(site_url=site_url,
                       form_heading='Upload Profile Photo',
                       instruction='Cover photo must be at least 200px tall and 200px wide.',
                       action=reverse('profile:update_profile_photo'),
                       form=form,
                       user_profile=user_profile))


@login_required
def update_card(request):
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    # load existing card info
    user_profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        card_form = ProfileCardForm(request.POST, instance=user_profile)
        if card_form.is_valid():
            card_form.save()
            return HttpResponseRedirect(reverse('profile:profile'))
    else:
        card_form = ProfileCardForm(instance=user_profile)

    return render(request,
                  'eprofile/update_form.html',
                  dict(site_url=site_url,
                       form_title='Update Profile Card Information',
                       form_action=reverse('profile:update_card'),
                       form=card_form,
                       user_profile=user_profile))


@login_required
def update_summary(request):
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    # pro = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        summary_form = ProfileSummaryForm(request.POST, instance=user_profile)
        if summary_form.is_valid():
            summary_form.save()
            return HttpResponseRedirect(reverse('profile:profile')+"#tab_summary")

    else:
        summary_form = ProfileSummaryForm(instance=user_profile)
    return render(request,
                  'eprofile/update_form.html',
                  dict(site_url=site_url,
                       form_title='Update Profile Summary',
                       form_action=reverse('profile:update_summary'),
                       form=summary_form,
                       user_profile=user_profile))


@login_required
def update_school(request, uuid=None):
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    form_title='Add a college/school'
    form_action=reverse('profile:update_school')
    if request.POST:
        if not uuid:
            # must be a new school
            school = Education(user=user_profile)
            school_form = EducationForm(request.POST, instance=school)
        else:
            school = Education.objects.get(Q(user=user_profile) & Q(uuid=uuid))
            # some one may have tried to hack db
            if school:
                school_form = EducationForm(request.POST, instance=school)
            else:
                return HttpResponseRedirect(reverse('profile:profile'))

        if school_form.is_valid():
            school_form.save()
            return HttpResponseRedirect(reverse('profile:profile'))
    else:
        if uuid:
            # load existing data to update
            school = Education.objects.get(uuid=uuid)
            school_form = EducationForm(instance=school)
            form_title = 'Edit college/school'
            form_action = reverse('profile:update_school_uuid', kwargs={'uuid':uuid})
        else:
            school_form = EducationForm()

    return render(request,
                  'eprofile/school.html',
                  dict(site_url=site_url,
                       form_title=form_title,
                       form_action=form_action,
                       form=school_form,
                       user_profile=user_profile))


@login_required
def experience(request, uuid=None):
    site_url = utility.get_site_url(request)
    user_profile = Profile.objects.get(user=request.user)
    form_title='Add a position'
    form_action=reverse('profile:experience')
    if request.POST:
        if not uuid:
            # must be a new position
            exp = Experience(user=user_profile)
            exp_form = ExperienceForm(request.POST, instance=exp)
        else:
            exps = Experience.objects.filter(Q(user=user_profile) & Q(uuid=uuid))
            if exps:
                exp = exps[0]
                exp_form = EducationForm(request.POST, instance=exp)
            else:
                # some one may be trying to hack ?
                return HttpResponseRedirect(reverse('profile:profile')+"#tab_experience")

        if exp_form.is_valid():
            exp_form.save()
            return HttpResponseRedirect(reverse('profile:profile'))
    else:
        if uuid:
            # load existing data to update
            exp = Experience.objects.get(uuid=uuid)
            exp_form = EducationForm(instance=exp)
            form_title = 'Edit position'
            form_action = reverse('profile:update_experience', kwargs={'uuid':uuid})
        else:
            exp_form = ExperienceForm()

    return render(request,
                  'eprofile/experience.html',
                  dict(site_url=site_url,
                       form_title=form_title,
                       form_action=form_action,
                       form=exp_form,
                       user_profile=user_profile))

eprofile/templates/eprofile/__base.html
{% load main_extras %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    {%block meta_tags  %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% endblock meta_tags %}

    <title>{% block title %}{% brand_name %}{% endblock title %}</title>
    {% block stylesheets %}
        <link rel="icon" href="{% static 'main/img/favicon.ico' %}" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
              crossorigin="anonymous">
        <!-- Custom CSS -->
        <link href="{% static 'eprofile/css/base.css' %}" rel="stylesheet" />
        <link href="{% static 'eprofile/css/profile.css' %}" rel="stylesheet" />
    {% endblock stylesheets %}
    <!-- other head contents such as css -->
    {% block head_extra %} {% endblock head_extra %}
</head>

<body>
<!-- main navigation bar -->
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ site_url }}">{% brand_name %}</a>
        </div>
        {% block header_extra %}{% endblock header_extra %}
    </div>
</header>
{% block navigation %}{% endblock navigation %}
<!-- main content of the page -->
<div id="main" role="main">
    <div class="container">
    <div class="row">
        {% block content %}{% endblock content %}
    </div>
    </div>
</div>

<div class="page-footer">
    {% include 'eprofile/_footer.html' %}
    {% block footer_extra %}{% endblock footer_extra %}
</div>
{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

{% endblock javascript %}
</body>
</html>

eprofile/templates/eprofile/_about.html
{% load main_extras %}
<div class="tab-pane fade" id="About">
    <div class="vertical-tabs-container">
        <ul class="nav nav-tabs vertical-nav-tabs">
            <li class="active"><a href="#tab_summary" data-toggle="tab">Summary</a></li>
            <li><a href="#tab_education" data-toggle="tab">Education</a></li>
            <li><a href="#tab_experience" data-toggle="tab">Work Experience</a></li>
        </ul>
        <div class="tab-content">
            <div id="tab_summary" class="section tab-pane vertical-tab-pane active">
                <div class="editContainer">
                    <a href="{% url 'profile:update_summary' %}">
                        <button class="btn btn-sm btn-info">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> | Edit summary
                        </button>
                    </a>
                </div>

                <h3>Summary</h3>
                <hr class="heading">
                <div class="sectionContent">
                    {{ user_profile.summary|linebreaksbr }}
                </div>
            </div>
            <div id="tab_education" class="section tab-pane vertical-tab-pane">
                <div class="editContainer">
                    <a href="{% url 'profile:update_school' %}">
                        <button class="btn btn-sm btn-info">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"
                          data-placement="left"></span> | Add a college/school
                        </button>
                    </a>
                </div>
                <h3> <span class="glyphicon glyphicon-education" aria-hidden="true"></span> Education</h3>
                <hr>
                {% if user_profile.schools %}
                    {% for school in user_profile.schools %}
                        <div class="subSection">
                            <div class="editContainer">
                                <a class="btn btn-sm btn-info"
                                   href="{% url 'profile:update_school' %}{{ school.uuid }}">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"
                                data-placement="left"></span> | Edit
                                </a>
                            </div>
                            <h4>{{ school.school }}</h4>
                            <h5>{% if school.location %}{{ school.location }}{% else %}Add location{% endif %}
                            </h5>
                            <h5>{% if school.degree %}{{ school.degree }}, {% else %}Add Degree,{% endif %}
                                {% if school.major_field %}{{ school.major_field }}{% else %}Add Major Field{% endif %}
                            </h5>
                            <h6>{{ school.month_from|month_name }}
                                {% if school.year_from %} {{ school.year_from }}{% else %}Add year {% endif %} -
                                {{ school.month_to|month_name }} {{ school.year_to }}
                            </h6>
                            <h6><label>GPA:</label> {% if school.gpa %}{{ school.gpa }}{% else %}Add GPA{% endif %}</h6>
                            <p><label>Concentrations:</label> {% if school.concentrations %}{{ school.concentrations|linebreaksbr  }}{% else %}
                                Add Concentrations{% endif %}</p>
                            <p><label>Societies:</label> {% if school.societies %}{{ school.societies|linebreaksbr  }}
                            {% else %}Add Societies{% endif %}</p>
                            <p><label>Activities:</label> {% if school.activities %}{{ school.activities|linebreaksbr  }}{% else %}Add Activities
                            {% endif %}</p>
                            <p><label>Description:</label> {% if school.description %}{{ school.description|linebreaksbr  }}{% else %}
                            Add Description{% endif %}</p>
                            <hr>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
         <div id="tab_experience" class="section tab-pane vertical-tab-pane">
                <div class="editContainer">
                    <a href="{% url 'profile:experience' %}">
                        <button class="btn btn-sm btn-info">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"
                          data-placement="left"></span> | Add a position
                        </button>
                    </a>
                </div>
                <h3> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Work Experience</h3>
                <hr>
                {% if user_profile.positions %}
                    {% for position in user_profile.positions %}
                        <div class="subSection">
                            <div class="editContainer">
                                <a class="btn btn-sm btn-info"
                                   href="{% url 'profile:update_education' %}{{ position.uuid }}">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"
                                data-placement="left"></span> | Edit
                                </a>
                            </div>
                            <h4>{{ position.title }}</h4>
                            <h5>{{ position.company }}</h5>
                            <h6>{% if position.location %}{{ position.location }}{% else %}Add location{% endif %}</h6>
                            <h6>{{ position.month_from|month_name }} {{ position.year_from }}
                                {% if position.current %}Present{% else %} -
                                {{ position.month_to|month_name }} {{ position.year_to }}
                                {% endif %}
                            </h6>
                            <h6 style="margin-bottom:0;"><label>Description:</label></h6>
                            <p>{% if school.description %}{{ school.description|linebreaksbr }}{% else %}
                            Add Description{% endif %}
                            </p>
                            <hr>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

eprofile/templates/eprofile/_footer.html
{% load main_extras %}
&copy; {% brand_name %}, {% current_year %} |
        <a href="#">User Agreement</a> |
        <a href="#">Privacy Policy</a>

eprofile/templates/eprofile/_header.html
{% load staticfiles %}
<div id="navbar">
    <form class="navbar-form navbar-left" role="search">
        <div class="input-group bannerSearch">
            <input type="text" class="form-control" aria-label="Search" style="width:100%;"
                   placeholder="Search universities, programs, people, business...">
            <div class="input-group-btn">
                <a class="btn btn-default" href="/dummy_search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
            </div>
        </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="dropdown-toggle btn-lg" data-toggle="dropdown" role="button" aria-expanded="false"><span
                class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'profile:edit_profile' %}">Edit Profile</a></li>
            </ul>
        </li>
        <li>
            <a href="{% url 'profile:profile' %}"><img src="
                {% if user_profile.profile_photo %}
                    {{ MEDIA_URL }}{{ user_profile.profile_photo }}
                {% else %}
                    {% static 'eprofile/img/profile.png' %}
                {% endif %}"
                                                       style="width:20px; padding-right:5px;"/>{{ user_profile.user.first_name }}
            </a>
        </li>
        <li><a href="/">Home</a></li>
        <li><a class="btn-lg" href="#"><span class="glyphicon glyphicon-bell" aria-hidden="true"></span></a></li>
        <li><a class="btn-lg" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></li>
        <li><a class="btn-lg" href="#"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle btn-lg" data-toggle="dropdown" role="button"
               aria-expanded="false"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span
                    class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">{{ user_profile.user.username }}</a></li>
                <li><a href="#">Settings</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-out"
                                                               aria-hidden="true"></span> Log out</a></li>
            </ul>
        </li>
    </ul>
</div>

eprofile/templates/eprofile/_nav.html
<nav class="navbar navbar-inverse navbar-static-top menu">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li class="dropdown">
                <a href="/profile/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspop="true"
                   aria-expanded="false">Profile <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/profile/edit/">Edit Profile</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="/profile/connections/" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspop="true" aria-expanded="false">Connections <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/profile/add_connection/">Add Connection</a></li>
                    <li><a href="/profile/find_alumni/">Find Alumni</a></li>

                </ul>
            </li>
            <li><a href="/jobs/">Jobs</a></li>
        </ul>
    </div>
</nav>

eprofile/templates/eprofile/_timeline.html
<div class="tab-pane fade in active" id="Timeline">
    <div class="main">
        <div class="section">
            <h4 class="title">Update Status</h4>
            <hr class="heading">
            <form class="login statusForm" method="POST" action="">
                {% csrf_token %}
                <textarea style="width:100%;" rows="3" placeholder="What are you up to?" required> </textarea>
                <hr>
                <button class="btn btn-primary" type="submit">Post</button>
            </form>
        </div>

        <div class="section">
            <h4 class="title">Show all the updates I shared...</h4>

        </div>
    </div>
</div>

eprofile/templates/eprofile/home.html
{% extends "eprofile/__base.html" %}
{% block title %}{{ block.super }} | Home{% endblock title %}

{% block header_extra %}
    {% include 'eprofile/_header.html' %}
{% endblock header_extra %}
{% block navigation %}
{% endblock navigation %}
{% block content %}
    <h1>Here you'll see the wall!</h1>
{% endblock content %}

eprofile/templates/eprofile/profile.html
{% extends "eprofile/__base.html" %}
{% load staticfiles %}

{% block title %}{{ block.super }} | Profile{% endblock title %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'eprofile/css/vertical_tab.css' %}" rel="stylesheet" />
{% endblock stylesheets %}
{% block header_extra %}
    {% include 'eprofile/_header.html' %}
{% endblock header_extra %}
{% block navigation %}
{% endblock navigation %}
{% block content %}
    {% include 'eprofile/_banner.html' %}
     <div class="tab-content">
        {% include 'eprofile/_timeline.html' %}
        {% include 'eprofile/_about.html' %}
    </div>
{% endblock content %}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'eprofile/js/profile.js' %}"></script>
{% endblock javascript %}