account/urls.py
from django.conf.urls import url

from account import views

app_name = 'account'

urlpatterns = [
    url(r'^recover/', views.recover, name='recover'),
    url(r'^reset_password/$', views.reset_password, name='reset_password'),
    url(r'^reset_password/(?P<key>.*)/$', views.reset_password, name='reset_password_key'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^activate/(.*)/$', views.activate, name='activate'),
    url(r'^activation$', views.activation, name='activation'),
]

konect/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import patterns, include, url
from django.contrib import admin


from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^profile/', include('eprofile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url

from main import views
from eprofile import views as pView

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', pView.home, name='home'),
    url(r'^index/$', pView.home, name='default'),
]

main/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here... do not use this UserProfile...user Profile Model
class UserProfile(models.Model):
    #foreign key to tie this info to the user
    user = models.OneToOneField(User)
    activation_key = models.CharField(max_length=128)
    key_expires = models.DateTimeField(null=True)
    #used to track language preference when we implement it
    locale = models.CharField(max_length=10, null= True)
    #Holds a profile picture on our site
    profile_picture = models.CharField(max_length=256, null=True)
    # Holds their current position e.g. faculty, student, data analyst
    current_title = models.CharField(max_length=100, null=True)
    #This holds the users publicly shared email, after all they may not want to publicise their personal emailmodels
    public_email = models.CharField(max_length=256, null=True)
    #Holds the user set banner picture
    banner_picture = models.CharField(max_length=256, null=True)
    #holds tagline
    tagline=models.CharField(max_length=100, null=True)
    #phoneNumber
    phone = models.CharField(max_length=30, null=True)


    def __str__(self):
        return self.user.email

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    # email = forms.charField(validators=[validators.EmailValidator, is_valid_username])

    class Meta:
        model = User

        fields = ('first_name', 'last_name', 'email', 'password')


    def is_valid_username(self, field_data, all_data):
        try:
            User.objects.get(email=field_data)
        except User.DoesNotExist:
            return True
        else:
            raise validators.ValidationError('The email "%s" already exists.'%field_data)

    def save(self, new_data):
        u = User.objects.create(username=new_data['email'], password=new_data['password'],
                                first_name=new_data['first_name'], last_name=new_data['last_name'])
        u.is_active = False
        u.is_staff = False
        u.is_superuser = False
        u.save()
        return u

main/views.py
from django.shortcuts import render, redirect
from main import utility

from eprofile.models import Profile

# Create your views here.

def index(request):
    site_url = utility.get_site_url(request)
    if request.user.is_authenticated():
        #return redirect(reverse('profile:home'))
        user_profile = Profile.objects.get(user=request.user)
        site_url = utility.get_site_url(request)
        return render(request,
                  'eprofile/home.html',
                  dict(user_profile=user_profile, site_url=site_url,))
    else:
        return render(request,
                      'account/login_signup.html',
                      {
                          'site_url': site_url,
                      })

main/templates/main/__base.html
{% load main_extras %}
{% load staticfiles i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    {%block meta_tags  %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% endblock meta_tags %}

    <title>{% block title %}{% brand_name %}{% endblock title %}</title>
    {% block stylesheets %}
        <link rel="icon" href="{% static 'main/img/favicon.ico' %}" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
              crossorigin="anonymous">
        <!-- Custom CSS -->
        <link href="{% static 'main/css/custom.css' %}" rel="stylesheet" />
    {% endblock stylesheets %}
    <!-- other head contents such as css -->
    {% block head_extra %} {% endblock head_extra %}
</head>

<body>
<!-- main navigation bar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% block site_link %}{% endblock site_link %}">{% brand_name %}</a>
        </div>
        {% block nav_extra %}{% endblock nav_extra %}
    </div>
</nav>
<!-- main content of the page -->
<div id="main" role="main">
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</div>

<footer>
    {% include 'main/_footer.html' %}
    {% block footer_extra %}{% endblock footer_extra %}
</footer>
{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% endblock javascript %}
</body>
</html>

main/templates/main/_nav_login.html
<div id="navbar">
    <form class="navbar-form navbar-right" action={% url "main:login" %} method="post">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" placeholder="Email" name="username" id="username" class="form-control" required>
        </div>
        <div class="form-group">
            <input type="password" name="password" id="password" placeholder="Password" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-success">Log In</button>
        <a class="navbar-link" href="{% url 'account:recover' %}">Forgot Password?</a>
    </form>
</div><!--/.navbar-collapse -->

main/templates/main/_signup.html
<div id="form_container">
    <h1>Sign Up</h1>
    <h3>It's Free...</h3>
    <hr>
    {% if error_message %}
        <div class="alert alert-danger fade in center" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ error_message | safe }}
        </div>
    {% endif %}
    <form class="form form-inline" role="form" action="{% url 'main:signup' %}" method="post">
        {% csrf_token %}
        <table class="form">
            <tr>
                <td><label for="first_name">First name:</label></td>
                <td>
                    <input type="text" class="form-control" name="first_name" id="first_name"
                           placeholder="First name" value="{{ first_name }}"required>
                </td>
            </tr>
            <tr>
                <td><label for="last_name">Last name:</label></td>
                <td>
                    <input type="text" class="form-control" name="last_name" id="last_name"
                           placeholder="Last name" value="{{ last_name }}" required>
                </td>
            </tr>
            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="email" class="form-control" name="email" id="email"
                       placeholder="Email" value="{{ email }}" required>
                </td>
            </tr>
            </tr>
            <tr>
                <td><label for="password">Password:</label></td>
                <td><input type="password" class="form-control" name="password" id="password"
                       placeholder="Password" value="{{ password }}"required>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><button type="submit" class="btn-lg btn-success btn-block">Sign up</button></td>
            </tr>
        </table>
    </form>
</div>

main/templates/main/index.html
{% extends "main/__base.html" %}

{% block title %}{{  block.super }} | Professional connection on a personal level {% endblock title %}

{% block site_link %}{{ site_url |safe }}{% endblock site_link %}
{% block nav_extra %}
    {% include 'main/_nav_login.html' %}
{% endblock nav_extra %}

{% block content %}
    {% include 'main/_signup.html' %}
{% endblock content %}

main/templates/main/login.html
{% extends "main/__base.html" %}
{% load main_extras %}

{% block title %}{{ block.super }} | Log In{% endblock title %}

{% block site_link %}{{ site_url |safe }}{% endblock site_link %}

{% block content %}
    <div class="row">
        <div id="form_container">
            <h3>{% brand_name %} Log In</h3>
            <hr>
            {% if error_message %}
                <div class="alert alert-danger fade in form-group center" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    {{ error_message }}
                </div>
            {% endif %}
            <form class="form form-inline" role="form" action="{% url 'main:login' %}" method="post">
                {% csrf_token %}
                <table class="form">
                    <tr>
                        <td><label for="username">Email:</label></td>
                        <td>
                            <input type="text" class="form-control" name="username" id="first_name"
                                   placeholder="Email" value="{{ email }}"required>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="password">Password:</label></td>
                        <td>
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="Password" value="{{ password }}"required>
                        </td>
                    </tr>

                    <tr>
                        <td>&nbsp;</td>
                        <td><button type="submit" class="btn btn-success">Log In</button> or
                            <a href="{% url 'main:signup' %}">Sign up</a></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td><a href="{% url 'account:recover' %}">Forgot Password?</a></td>
                    </tr>
                </table>
            </form>

        </div>
    </div>
{% endblock content %}

main/templates/main/login_signup.html
{% extends "main/__base.html" %}

{% block title %}{{  block.super }} | Professional connection on a personal level {% endblock title %}

{% block site_link %}{{ site_url |safe }}{% endblock site_link %}
{% block nav_extra %}
    {% include 'main/_nav_login.html' %}
{% endblock nav_extra %}

{% block content %}
    {% include 'main/_signup.html' %}
{% endblock content %}

main/templates/main/message.html
{% extends 'main/__base.html' %}

{% block title %}{{ block.super }} | Message {% endblock title %}
{% block site_link %}{{ site_url |safe }}{% endblock site_link %}

{% block content %}
    {% if message_type == 'success' %}
        <div class="alert alert-success" role="alert">
            {{ message|safe }}
        </div>
    {% elif message_type == 'info' %}
        <div class="alert alert-info" role="alert">
            {{ message|safe }}
        </div>
    {% elif message_type == 'warning' %}
        <div class="alert alert-warning" role="alert">
            {{ message|safe }}
        </div>
    {% else %}
        <div class="alert alert-danger" role="alert">
            {{ message|safe }}
        </div>
    {% endif %}

{% endblock content %}

main/templates/main/profile.html
{% extends "main/__base.html" %}
{% block title %}Konect | Profile{% endblock title %}

{% block domain %}{{ domain |safe }}{% endblock domain %}

{% block content %}
<h1>Welcome to your profile!</h1>
{% endblock content %}

main/templates/main/signup.html
{% extends "main/__base.html" %}

{% block title %}{{ block.super }} | Sign Up{% endblock title %}

{% block site_link %}{{ site_url |safe }}{% endblock site_link %}

{% block content %}
    {% include 'main/_signup.html' %}
{% endblock content %}